first_homepage:
    pattern:  /brendan/hello/{name}
    defaults: { _controller: FirstBundle:Default:index }

landing_page:
    pattern: /brendan/landing
    defaults: { _controller: FirstBundle:BrendanSite:landing }

mongoDB:
    pattern: /brendan/mongo
    defaults: { _controller: FirstBundle:BrendanSite:mongo }

SQlite:
    pattern: /brendan/sqlite
    defaults: { _controller: FirstBundle:BrendanSite:sqlite }
